package main

import (
	"fmt"
	"log"
	"os"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

func main() {
	config := loadConfig("codegen.yaml")
	if err := generateCode(config); err != nil {
		panic(err)
	}
}

func loadConfig(path string) *Config {
	// read configuration file
	data, err := os.ReadFile(path)
	if err != nil {
		log.Fatalf("failed to read config %s: %v", path, err)
	}

	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		log.Fatalf("failed to parse config: %v", err)
	}

	cfg.CalculateChildren()
	cfg.PopulateProperties()

	return &cfg
}

func generateCode(config *Config) error {
	// header
	fmt.Println("//go:build js && wasm")
	fmt.Println()
	fmt.Println("// Code generated by codegen.go; DO NOT EDIT.")
	fmt.Println("package jsrt")
	fmt.Println()
	fmt.Println("import \"syscall/js\"")

	for _, typeCfg := range config.Types {
		if err := generateType(typeCfg); err != nil {
			return err
		}
	}

	return nil
}

var typeTemplate = template.Must(template.New("type").Funcs(template.FuncMap{
	"capitalize": capitalize,
	"getter":     getter,
}).Parse(`
///// {{capitalize .Name}} /////

type {{.Name}} struct {
{{- if .Parent}}
	*{{.Parent}}
{{- else}}
	*wrapper
{{- end}}
}

func new{{capitalize .Name}}(value js.Value) *{{.Name}} {
	if value.IsNull() {
		return nil
	}
	{{- if .Parent}}
	return &{{.Name}}{new{{capitalize .Parent}}(value)}
	{{- else}}
	return &{{.Name}}{newWrapper(value)}
	{{- end}}
}

func wrap{{capitalize .Name}}(value js.Value) {{capitalize .Name}} {
	switch {
{{- range .Children}}
	case instanceOf(value, "{{capitalize .}}"):
		return wrap{{capitalize .}}(value)
{{- end}}
	default:
		return new{{capitalize .Name}}(value)
	}
}

{{- if .Properties}}
{{range $name,$typ := .Properties}}
func (t *{{$.Name}}) Get{{capitalize $name}}() {{$typ}} {
	return {{getter $typ $name}}
}
func (t *{{$.Name}}) Set{{capitalize $name}}(v {{$typ}}) {
	t.Set("{{$name}}", v)
}
{{end}}
{{- end}}
`))

func generateType(typeCfg TypeConfig) error {
	return typeTemplate.Execute(os.Stdout, typeCfg)
}

type Config struct {
	Types      []TypeConfig
	Properties map[string]map[string]string
}

type TypeConfig struct {
	Name       string
	Parent     *string
	Children   []string          // calculated programmatically
	Properties map[string]string // property name -> type (from config)
}

func (c *Config) CalculateChildren() {
	for i := range c.Types {
		c.Types[i].Children = nil
	}

	indexByName := make(map[string]int)
	for i := range c.Types {
		indexByName[c.Types[i].Name] = i
	}

	for i := range c.Types {
		if c.Types[i].Parent != nil {
			parentName := *c.Types[i].Parent
			parentIndex, ok := indexByName[parentName]
			if ok {
				c.Types[parentIndex].Children = append(c.Types[parentIndex].Children, c.Types[i].Name)
			}
		}
	}
}

func (c *Config) PopulateProperties() {
	indexByName := make(map[string]int)
	for i := range c.Types {
		indexByName[c.Types[i].Name] = i
	}

	for _type, props := range c.Properties {
		index, ok := indexByName[_type]
		if !ok {
			log.Printf("warning: type %s not found for properties", _type)
			continue
		}
		c.Types[index].Properties = props
	}
}

func capitalize(s string) string {
	if len(s) == 0 {
		return s
	}

	for _, w := range []string{
		"html",
		"ui",
		"id",
	} {
		if strings.HasPrefix(s, w) {
			return strings.ToUpper(w) + s[len(w):]
		}
	}

	return string(s[0]-32) + s[1:]
}

func getter(typ, name string) string {
	val := fmt.Sprintf("t.Get(\"%s\")", name)

	switch typ {
	case "float64":
		return val + ".Float()"
	case "string":
		return val + ".String()"
	case "bool":
		return val + ".Bool()"
	case "int":
		return val + ".Int()"
	case "uint":
		return "uint(" + val + ".Int())"
	default:
		panic(fmt.Sprintf("unsupported type for getter conversion: %s", typ))
	}
}
