package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

func main() {
	config := loadConfig("codegen.yaml")
	if err := generateCode(config); err != nil {
		panic(err)
	}
}

func loadConfig(path string) *Config {
	// read configuration file
	data, err := ioutil.ReadFile(path)
	if err != nil {
		log.Fatalf("failed to read config %s: %v", path, err)
	}

	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		log.Fatalf("failed to parse config: %v", err)
	}

	cfg.CalculateChildren()

	return &cfg
}

func generateCode(config *Config) error {
	// header
	fmt.Println("//go:build js && wasm")
	fmt.Println()
	fmt.Println("// Code generated by codegen.go; DO NOT EDIT.")
	fmt.Println("package jsrt")
	fmt.Println()
	fmt.Println("import \"syscall/js\"")

	for _, typeCfg := range config.Types {
		if err := generateType(typeCfg); err != nil {
			return err
		}
	}

	return nil
}

var typeTemplate = template.Must(template.New("type").Funcs(template.FuncMap{
	"capitalize": capitalize,
}).Parse(`
///// {{capitalize .Name}} /////

type {{.Name}} struct {
{{- if .Parent}}
	*{{.Parent}}
{{- else}}
	*wrapper
{{- end}}
}

func new{{capitalize .Name}}(value js.Value) *{{.Name}} {
	if value.IsNull() {
		return nil
	}
	{{- if .Parent}}
	return &{{.Name}}{new{{capitalize .Parent}}(value)}
	{{- else}}
	return &{{.Name}}{newWrapper(value)}
	{{- end}}
}

func wrap{{capitalize .Name}}(value js.Value) {{capitalize .Name}} {
	switch {
{{- range .Children}}
	case instanceOf(value, "{{capitalize .}}"):
		return wrap{{capitalize .}}(value)
{{- end}}
	default:
		return new{{capitalize .Name}}(value)
	}
}
`))

func generateType(typeCfg TypeConfig) error {
	return typeTemplate.Execute(os.Stdout, typeCfg)
}

type Config struct {
	Types []TypeConfig
}

type TypeConfig struct {
	Name     string
	Parent   *string
	Children []string // calculated programmatically
}

func (c *Config) CalculateChildren() {
	for i := range c.Types {
		c.Types[i].Children = nil
	}

	indexByName := make(map[string]int)
	for i := range c.Types {
		indexByName[c.Types[i].Name] = i
	}

	for i := range c.Types {
		if c.Types[i].Parent != nil {
			parentName := *c.Types[i].Parent
			parentIndex, ok := indexByName[parentName]
			if ok {
				c.Types[parentIndex].Children = append(c.Types[parentIndex].Children, c.Types[i].Name)
			}
		}
	}
}

func capitalize(s string) string {
	if len(s) == 0 {
		return s
	}

	if strings.HasPrefix(s, "html") {
		return "HTML" + s[4:]
	}

	if strings.HasPrefix(s, "ui") {
		return "UI" + s[2:]
	}

	return string(s[0]-32) + s[1:]
}
