//go:build js && wasm

// Code generated by codegen.go; DO NOT EDIT.
package jsrt

import "syscall/js"

///// CharacterData /////

type characterData struct {
	*node
}

func newCharacterData(value js.Value) *characterData {
	if value.IsNull() {
		return nil
	}
	return &characterData{newNode(value)}
}

func wrapCharacterData(value js.Value) CharacterData {
	switch {
	case instanceOf(value, "Text"):
		return wrapText(value)
	default:
		return newCharacterData(value)
	}
}

///// Document /////

type document struct {
	*node
}

func newDocument(value js.Value) *document {
	if value.IsNull() {
		return nil
	}
	return &document{newNode(value)}
}

func wrapDocument(value js.Value) Document {
	switch {
	default:
		return newDocument(value)
	}
}

///// Element /////

type element struct {
	*node
}

func newElement(value js.Value) *element {
	if value.IsNull() {
		return nil
	}
	return &element{newNode(value)}
}

func wrapElement(value js.Value) Element {
	switch {
	case instanceOf(value, "HTMLElement"):
		return wrapHTMLElement(value)
	default:
		return newElement(value)
	}
}

///// HTMLElement /////

type htmlElement struct {
	*element
}

func newHTMLElement(value js.Value) *htmlElement {
	if value.IsNull() {
		return nil
	}
	return &htmlElement{newElement(value)}
}

func wrapHTMLElement(value js.Value) HTMLElement {
	switch {
	case instanceOf(value, "HTMLInputElement"):
		return wrapHTMLInputElement(value)
	default:
		return newHTMLElement(value)
	}
}

///// HTMLInputElement /////

type htmlInputElement struct {
	*htmlElement
}

func newHTMLInputElement(value js.Value) *htmlInputElement {
	if value.IsNull() {
		return nil
	}
	return &htmlInputElement{newHTMLElement(value)}
}

func wrapHTMLInputElement(value js.Value) HTMLInputElement {
	switch {
	default:
		return newHTMLInputElement(value)
	}
}

///// KeyboardEvent /////

type keyboardEvent struct {
	*uiEvent
}

func newKeyboardEvent(value js.Value) *keyboardEvent {
	if value.IsNull() {
		return nil
	}
	return &keyboardEvent{newUIEvent(value)}
}

func wrapKeyboardEvent(value js.Value) KeyboardEvent {
	switch {
	default:
		return newKeyboardEvent(value)
	}
}

///// Node /////

type node struct {
	*eventTarget
}

func newNode(value js.Value) *node {
	if value.IsNull() {
		return nil
	}
	return &node{newEventTarget(value)}
}

func wrapNode(value js.Value) Node {
	switch {
	case instanceOf(value, "CharacterData"):
		return wrapCharacterData(value)
	case instanceOf(value, "Document"):
		return wrapDocument(value)
	case instanceOf(value, "Element"):
		return wrapElement(value)
	default:
		return newNode(value)
	}
}

///// Text /////

type text struct {
	*characterData
}

func newText(value js.Value) *text {
	if value.IsNull() {
		return nil
	}
	return &text{newCharacterData(value)}
}

func wrapText(value js.Value) Text {
	switch {
	default:
		return newText(value)
	}
}

///// UIEvent /////

type uiEvent struct {
	*event
}

func newUIEvent(value js.Value) *uiEvent {
	if value.IsNull() {
		return nil
	}
	return &uiEvent{newEvent(value)}
}

func wrapUIEvent(value js.Value) UIEvent {
	switch {
	case instanceOf(value, "KeyboardEvent"):
		return wrapKeyboardEvent(value)
	default:
		return newUIEvent(value)
	}
}

///// Console /////

type console struct {
	*wrapper
}

func newConsole(value js.Value) *console {
	if value.IsNull() {
		return nil
	}
	return &console{newWrapper(value)}
}

func wrapConsole(value js.Value) Console {
	switch {
	default:
		return newConsole(value)
	}
}

///// Event /////

type event struct {
	*wrapper
}

func newEvent(value js.Value) *event {
	if value.IsNull() {
		return nil
	}
	return &event{newWrapper(value)}
}

func wrapEvent(value js.Value) Event {
	switch {
	case instanceOf(value, "UIEvent"):
		return wrapUIEvent(value)
	default:
		return newEvent(value)
	}
}

///// EventTarget /////

type eventTarget struct {
	*wrapper
}

func newEventTarget(value js.Value) *eventTarget {
	if value.IsNull() {
		return nil
	}
	return &eventTarget{newWrapper(value)}
}

func wrapEventTarget(value js.Value) EventTarget {
	switch {
	case instanceOf(value, "Node"):
		return wrapNode(value)
	default:
		return newEventTarget(value)
	}
}

///// HTMLCollection /////

type htmlCollection struct {
	*wrapper
}

func newHTMLCollection(value js.Value) *htmlCollection {
	if value.IsNull() {
		return nil
	}
	return &htmlCollection{newWrapper(value)}
}

func wrapHTMLCollection(value js.Value) HTMLCollection {
	switch {
	default:
		return newHTMLCollection(value)
	}
}

///// TokenList /////

type tokenList struct {
	*wrapper
}

func newTokenList(value js.Value) *tokenList {
	if value.IsNull() {
		return nil
	}
	return &tokenList{newWrapper(value)}
}

func wrapTokenList(value js.Value) TokenList {
	switch {
	default:
		return newTokenList(value)
	}
}
